### ISSUE TITLE
Subclassing subStep breaks event management

### ISSUE THREAD

**Issue by slibert** [tltv/gantt#24]
Hello,

I need to maintain some link between my table line and the substep I create in Gantt, to use it when user clicks on it.
As there is no setData on steps, I made a subclass of substep  : 

`
	public class TaskStep extends SubStep
	{
		Task task;
        }
`

With this kind of substep, Gantt is displaying without any trouble but click-event is broken : event object has no step ( event.getStep() always returns null )
I have the feeling this is something coming from uuid, so I tried to force uuid creation on my TaskStep object, but without any more success.

Regards

**Comment by tltv** [comment]
Task need to be Serializable, just like SubStep is. I suspect that Task is not serialized and therefore client side will fail and propably throws some exceptions and uses null value instead of TaskStep.

When you add new field into shared state object, which SubStep is, you need to also pay attention on how GWT can serialize it. Prefer using primitive types or their equivalent Object types. LIke String, long or Long, etc.

Putting entity or any other Java bean into shared state is not a good idea because it might lead into unexpected issues when changed entity/bean suddently breaks the serialization. And there will be unnecessary addition to the data being transered to the client browser.

**Comment by tltv** [comment]
Latest version 0.9.1 has Gantt.setData(AbstractStep,Object) and getData(AbstractStep). Try to use those instead of extending SubStep.
